global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: "rapidroads-backend"
    metrics_path: "/v1/metrics"
    scheme: http
    static_configs:
      - targets: ["backend-api:4000"]

  - job_name: "nginx"
    metrics_path: "/health"
    static_configs:
      - targets: ["nginx-proxy:80"]

rule_files: []
